### PR TITLE
Setting gulp to published 4.0.0 version

### PR DESCRIPTION
**Pull request by NickTsitlakidis**

### CODE REVIEW

**Comment by juha-h** [comment]
I noticed too that 'npm install' failed:
```
Unhandled rejection Error: Command failed: /usr/bin/git checkout 4.0 for readab
error: pathspec '4.0' did not match any file(s) known to git.
```
I solved it by removing #4.0 from the git url:
```
diff --git a/package.json b/package.json
index 84a2d4c..cd163b5 100644
--- a/package.json
+++ b/package.json
@@ -40,7 +40,7 @@
     "eslint": "^4.14.0",
     "eslint-plugin-import": "^2.8.0",
     "eslint-plugin-react": "7.5.1",
-    "gulp": "git://github.com/gulpjs/gulp.git#4.0",
+    "gulp": "git://github.com/gulpjs/gulp.git",
     "gulp-css-base64": "^1.3.4",
     "gulp-eslint": "^4.0.0",
     "gulp-header": "^1.8.9",
```

**Comment by NickTsitlakidis** [comment]
My apologies, I was under the impression that 4.0.0 was published but it looks like it's currently tagged as "next" in the gulp project. I believe that the current version in master is ok since it declares a specific version so I'm going to close the PR.

**Comment by juha-h** [comment]
package.json still needs to be fixed, e.g., like I have done in my local copy (shown in above).

**Comment by ibc** [comment]
The problem is that they have removed the "4.0" branch, so indeed it fails now. Moving it to `"gulp": "^4.0.0"` does indeed work (this is what I do in all my other projects). Commiting soon.

**Pull request closed without merging**
